### ISSUE TITLE
searchbar mkp homepage

### ISSUE THREAD

**Issue by djulien19** [Valeureux/wezer-custom#11]

**Comment by djulien19** [comment]
même couleur bleu que le fond pour les annonces
si possible diminuer la taille en hauteur
sinon mettre au milieu en hauteur le texte (remonter d'une ligne)

![search-mk](https://cloud.githubusercontent.com/assets/6325713/10262330/0a2770d0-69c4-11e5-8798-04795938dc80.jpg)

**Comment by djulien19** [comment]
celui ci le bleu Bleu : R = 219 / V = 229 / B = 242

**Comment by SybilleSG** [comment]
n’est pas plutôt ?

CORE  BleuGrisVert : pantone 5473  C, hex 115E67, R17 V94 B103, C86 M26 J33 N20

EXCHANGE    vert : pantone 361C, C72 M0 J100 N0, R113 V171 B63
    WANT    vert : pantone 361C, C72 M0 J100 N0, R113 V171 B63
    OFFER mauve/rose (opposé de vert) :  R240 V42 B190

EMERGENCE   bleu : pantone 7711C, C79 M17 J30 N0, R0 V160 B175 

---

Sybille Saint Girons
Présidente et co-fondatrice de l’ association Valeureux
sybille@valeureux.org
+33 (0) 663 541 967
skype/twitter : etoiledejoie

« Ensemble, contribuer à l’émergence, à la reconnaissance et au partage de toutes les forme de richesses au service de la Vie. »

Dernière parution : « L’intelligence collective, co-créons en conscience le monde de demain », Ed. Yves Michel http://www.yvesmichel.org/product-page/livres-a-paraitre/lintelligence-collective

valeureux.org, la fabrique participative d’outils, jeux et processus d’Actualisation de Richesses en bien commun pour les communautés. 

lanceur de la plateforme de coopération wezer.org

Help Wezer in contributions : https://www.wezer.org/marketplace/search
€uros : https://www.helloasso.com/associations/valeureux/collectes/support-wezer  
and FairCoin : http://getfaircoin.net/ with this wallet fECFqHiGr5AKa9poHDFHsNsQoiu1SbUTJd 

Aidez Valeureux en contributions : https://valeureux.wezer.org/marketplace/search
en €uros : https://www.helloasso.com/associations/valeureux/collectes/soutien-aux-actions-de-valeureux
et FairCoin : http://getfaircoin.net/ en utilisant ce porte-monnaie fY7Y7pAW7GiyGadhEAVWfNyKLuWGgwA98Q

https://www.facebook.com/sybille.girons
https://about.me/sybillesaintgirons
https://fr.linkedin.com/pub/sybille-saint-girons/8/b3/a68
https://twitter.com/etoiledejoie
http://www.viadeo.com/profile/0021wr2ved6w0uwn
https://plus.google.com/u/0/+SybilleSaintGirons/posts

—————

**Comment by djulien19** [comment]
Pour info

Le 6 octobre 2015 à 20:51:50, SybilleSG (notifications@github.com) a écrit:

n’est pas plutôt ?

CORE BleuGrisVert : pantone 5473 C, hex 115E67, R17 V94 B103, C86 M26 J33 N20

EXCHANGE vert : pantone 361C, C72 M0 J100 N0, R113 V171 B63
WANT vert : pantone 361C, C72 M0 J100 N0, R113 V171 B63
OFFER mauve/rose (opposé de vert) : R240 V42 B190

EMERGENCE bleu : pantone 7711C, C79 M17 J30 N0, R0 V160 B175

---

Sybille Saint Girons
Présidente et co-fondatrice de l’ association Valeureux
sybille@valeureux.org
+33 (0) 663 541 967
skype/twitter : etoiledejoie

« Ensemble, contribuer à l’émergence, à la reconnaissance et au partage de toutes les forme de richesses au service de la Vie. »

Dernière parution : « L’intelligence collective, co-créons en conscience le monde de demain », Ed. Yves Michel http://www.yvesmichel.org/product-page/livres-a-paraitre/lintelligence-collective

valeureux.org, la fabrique participative d’outils, jeux et processus d’Actualisation de Richesses en bien commun pour les communautés.

lanceur de la plateforme de coopération wezer.org

Help Wezer in contributions : https://www.wezer.org/marketplace/search
€uros : https://www.helloasso.com/associations/valeureux/collectes/support-wezer
and FairCoin : http://getfaircoin.net/ with this wallet fECFqHiGr5AKa9poHDFHsNsQoiu1SbUTJd

Aidez Valeureux en contributions : https://valeureux.wezer.org/marketplace/search
en €uros : https://www.helloasso.com/associations/valeureux/collectes/soutien-aux-actions-de-valeureux
et FairCoin : http://getfaircoin.net/ en utilisant ce porte-monnaie fY7Y7pAW7GiyGadhEAVWfNyKLuWGgwA98Q

https://www.facebook.com/sybille.girons
https://about.me/sybillesaintgirons
https://fr.linkedin.com/pub/sybille-saint-girons/8/b3/a68
https://twitter.com/etoiledejoie
http://www.viadeo.com/profile/0021wr2ved6w0uwn
https://plus.google.com/u/0/+SybilleSaintGirons/posts

—————

**Comment by florent-valeureux** [comment]
Fait avec bkg DBE5F2  / Bleu : R = 219 / V = 229 / B = 242
