### ISSUE TITLE
couleur bouton

### ISSUE THREAD

**Issue by djulien19** [Valeureux/wezer-custom#14]
une couleur identique pour tous les boutons Wezer
il y a du bleu et du vert.
tout mettre en vert ? je pense surotut aux deux en bas de page 
contactez-nous et celui pour le plan de site

**Comment by djulien19** [comment]
ou tout en bleu... ça a l'air de faire parti du thème choisi au départ

**Comment by florent-valeureux** [comment]
... tout en bleu, j'ai fait un essai en vert ce n'est pas beau surtout avec le graphisme du SEL
