### ISSUE TITLE
couleurs bandeau

### ISSUE THREAD

**Issue by djulien19** [Valeureux/wezer-custom#3]
Bienvenue onglet sélectionné : en rouge
réduire de moitié la barre de recherche en hauteur
même couleur bleu clair que les onglets

https://www.evernote.com/l/ACYQV3yWOHZHqKJajY_muxaSdcrnI3st3TM

**Comment by djulien19** [comment]
de même pour le bas de page footer

**Comment by florent-valeureux** [comment]
Rouge ? on ne verra plus le texte.
Peux-tu ouvrir une autre issue pour la barre de recherche

**Comment by florent-valeureux** [comment]
![2015-10-01 00_47_24-homepage _ sel audonien - waterfox](https://cloud.githubusercontent.com/assets/9918969/10208786/0f503b04-67d6-11e5-8208-1a2f6975b31c.png)
