### ISSUE TITLE
présentation want et offer sur mkp

### ISSUE THREAD

**Issue by djulien19** [Valeureux/wezer-custom#5]
mettre les deux logos ou le titre Offre / Demande au milieu

![demand](https://cloud.githubusercontent.com/assets/6325713/10208209/faa64490-67d1-11e5-83fb-ab8410272c20.png)
![offer](https://cloud.githubusercontent.com/assets/6325713/10208210/fabf328e-67d1-11e5-87e7-9e1786c77973.png)

https://www.evernote.com/l/ACYgXbIr7RBJu5n7vdwA0DY84_CRzQwOyig

**Comment by florent-valeureux** [comment]
Je n'ai pas compris comme avant ? 
![2015-10-01 00_50_06-website_marketplace mp_search _ sel audonien - waterfox](https://cloud.githubusercontent.com/assets/9918969/10208835/71f16b02-67d6-11e5-9678-ec6b49619d8a.png)

**Comment by SybilleSG** [comment]
j’avais fait 2 couleurs pour différencier O et W
merci de les retenir

CORE  BleuGrisVert : pantone 5473  C, hex 115E67, R17 V94 B103, C86 M26 J33 N20

EXCHANGE    vert : pantone 361C, C72 M0 J100 N0, R113 V171 B63
    WANT    vert : pantone 361C, C72 M0 J100 N0, R113 V171 B63
    OFFER mauve/rose (opposé de vert) :  R240 V42 B190

---

Sybille Saint Girons
Présidente et co-fondatrice de l’ association Valeureux
sybille@valeureux.org
+33 (0) 663 541 967
skype/twitter : etoiledejoie

« Ensemble, contribuer à l’émergence, à la reconnaissance et au partage de toutes les forme de richesses au service de la Vie. »

Dernière parution : « L’intelligence collective, co-créons en conscience le monde de demain », Ed. Yves Michel http://www.yvesmichel.org/product-page/livres-a-paraitre/lintelligence-collective

valeureux.org, la fabrique participative d’outils, jeux et processus d’Actualisation de Richesses en bien commun pour les communautés. 

lanceur de la plateforme de coopération wezer.org

Help Wezer in contributions : https://www.wezer.org/marketplace/search
€uros : https://www.helloasso.com/associations/valeureux/collectes/support-wezer  
and FairCoin : http://getfaircoin.net/ with this wallet fECFqHiGr5AKa9poHDFHsNsQoiu1SbUTJd 

Aidez Valeureux en contributions : https://valeureux.wezer.org/marketplace/search
en €uros : https://www.helloasso.com/associations/valeureux/collectes/soutien-aux-actions-de-valeureux
et FairCoin : http://getfaircoin.net/ en utilisant ce porte-monnaie fY7Y7pAW7GiyGadhEAVWfNyKLuWGgwA98Q

https://www.facebook.com/sybille.girons
https://about.me/sybillesaintgirons
https://fr.linkedin.com/pub/sybille-saint-girons/8/b3/a68
https://twitter.com/etoiledejoie
http://www.viadeo.com/profile/0021wr2ved6w0uwn
https://plus.google.com/u/0/+SybilleSaintGirons/posts

—————

**Comment by djulien19** [comment]
Au-dessus de chaque annonce, il y a le type : offre ou demande en texte aligné à gauche. Voir ma copie d'écran.
A la place, ça serait mieux d'avoir le logo en tout petit
ok pour différencier O/W par deux couleurs, pas sûr que les deux couleurs soient très adaptées avec la charte mais à tenter !

**Comment by SybilleSG** [comment]
## elles le sont

Sybille Saint Girons
Présidente et co-fondatrice de l’ association Valeureux
sybille@valeureux.org
+33 (0) 663 541 967
skype/twitter : etoiledejoie

« Ensemble, contribuer à l’émergence, à la reconnaissance et au partage de toutes les forme de richesses au service de la Vie. »

Dernière parution : « L’intelligence collective, co-créons en conscience le monde de demain », Ed. Yves Michel http://www.yvesmichel.org/product-page/livres-a-paraitre/lintelligence-collective

valeureux.org, la fabrique participative d’outils, jeux et processus d’Actualisation de Richesses en bien commun pour les communautés. 

lanceur de la plateforme de coopération wezer.org

Help Wezer in contributions : https://www.wezer.org/marketplace/search
€uros : https://www.helloasso.com/associations/valeureux/collectes/support-wezer  
and FairCoin : http://getfaircoin.net/ with this wallet fECFqHiGr5AKa9poHDFHsNsQoiu1SbUTJd 

Aidez Valeureux en contributions : https://valeureux.wezer.org/marketplace/search
en €uros : https://www.helloasso.com/associations/valeureux/collectes/soutien-aux-actions-de-valeureux
et FairCoin : http://getfaircoin.net/ en utilisant ce porte-monnaie fY7Y7pAW7GiyGadhEAVWfNyKLuWGgwA98Q

https://www.facebook.com/sybille.girons
https://about.me/sybillesaintgirons
https://fr.linkedin.com/pub/sybille-saint-girons/8/b3/a68
https://twitter.com/etoiledejoie
http://www.viadeo.com/profile/0021wr2ved6w0uwn
https://plus.google.com/u/0/+SybilleSaintGirons/posts

—————
